quarkus.http.port=8085
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=murrietaBD2025%
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/ordenes
# Borra y recrea las tablas al levantar
quarkus.hibernate-orm.database.generation=drop-and-create
# Ejecuta import.sql automáticamente
# Ver el SQL generado
quarkus.hibernate-orm.log.sql=true