quarkus.http.port=8081
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=murrietaBD2025%
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/catalagoproductos
# Borra y recrea las tablas al levantar
quarkus.hibernate-orm.database.generation=drop-and-create
# Ejecuta import.sql automáticamente
quarkus.hibernate-orm.sql-load-script=import.sql
# Ver el SQL generado
quarkus.hibernate-orm.log.sql=true